run_name: calo_eplus
dtype: float64
p_type: eplus

#Dataset
loader_module: calo_inn
loader_params: 
  p_type: eplus   # gammas, eplus, pions
  geant_file: /remote/gpu06/favaro/discriminator-metric/data/calo_cls_geant/full_cls_eplus.hdf5
  generated_file: /remote/gpu06/favaro/discriminator-metric/data/calo_bay_samples/samples_eplus.hdf5
  add_log_energy: True
  add_log_layer_ens: True
  add_logit_step: False
  add_cut: 0.0
  train_split: 0.6
  test_split: 0.2
  add_logp: False
  
# Model
activation: leaky_relu
negative_slope: 0.01
dropout: 0.0
layers: 3
hidden_size: 512

# Training
bayesian: False
prior_prec: 0.01
std_init: -9.0

lr: 1.e-3
betas: [0.9, 0.99]
weight_decay: 0.0
epochs: 150
batch_size: 512
lr_scheduler: reduce_on_plateau
lr_decay_factor: 0.1
lr_patience: 250
checkpoint_interval: 5

# Evaluation
bayesian_samples: 5
lower_cluster_thresholds: [0.1]
upper_cluster_thresholds: [2.0]

#Plotting
w_labels: [ placeh, Geant1, Geant2]
add_w_comb: False

