run_name: calo_inn

#Dataset
loader_module: calo_inn
loader_params: 
  geant_file: path_to_file.hdf5
  generated_file: path_to_file.hdf5
  add_log_energy: True
  add_log_layer_ens: True
  add_logit_step: False
  
# Model
activation: leaky_relu
negative_slope: 0.1
dropout: 0.1
layers: 5
hidden_size: 256

# Training
bayesian: False
lr: 1.e-3
betas: [0.9, 0.99]
weight_decay: 0.0
epochs: 50
batch_size: 1024
lr_scheduler: reduce_on_plateau
lr_decay_factor: 0.1
lr_patience: 5
checkpoint_interval: 5

# Evaluation
#bayesian_samples: 2
#lower_cluster_thresholds: [0.01, 0.1]
#upper_cluster_thresholds: [0.9, 0.99]
